spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/quickreaction
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100    # 이거는 무조건 켜주는게 좋다. 인쿼리의 갯수 (쿼리를 많이 줄여줌 )
                                          # 1000개의 쿼리라면 10번 루프가 돈다. 1 n m 이 1 1 1 이 된다. min 100 max 1000개라고 생각
  logging.level:
    org.hibernate.SQL: debug
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html